# Site settings
# These are used to personalize your new site.
title: Ponpawit Potisom # your name here
logo: "/images/Mark's Pic.jpeg" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2027)
  <br /><br />
  <a href="/pdf/Resume.pdf">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/ponpawit-potisom-a19a31316/">View My LinkedIn Profile</a>
repository: "ppotisom-pp.github.io"
github_username:  username # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

